apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: dev-rcp-1
  labels:
    name: prometheus-instance
    app: prometheus-app
    project: dev-rcp-1
spec:
  replicas: 2
  serviceAccountName: prometheus-sa
  securityContext: {}
  serviceMonitorSelector: 
    matchLabels:
      name: prometheus-service-monitor
    ruleSelector: {}