kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prometheus-route
  namespace: dev-rcp-1
  labels:
    name: prometheus-route
    app: prometheus-app
    project: dev-rcp-1
    operated-prometheus: "true"
spec:
  path: /
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None