apiVersion: v1
kind: Template
labels:
  template: demobackery
  group: demobackery
metadata:
  name: demobackery
  description: "Template containing application artifacts."
parameters:
- displayName: DEV_PROJECT name
  value: dev-demobakery
  name: DEV_PROJECT
  required: true
- displayName: Quay.io Image Repository
  description: Quay.io repository for pushing Tasks container images
  name: QUAY_REPOSITORY
  required: true
  value: demobakery
- displayName: Application name
  description: Name of the application
  name: APP_NAME
  required: true
- displayName: Application repository
  description: repository containing application code
  name: APP_REPO
  required: true
- displayName: Repository branch
  description: Code base branch
  name: APP_BRANCH
  required: true
- displayName: memory
  description: memory allocation
  name: MEMORY
  required: false
- displayName: cpu
  description: cpu allocation
  name: CPU
  required: false
- displayName: Application replicas
  description: number of application replicas
  name: REPLICAS
  required: false
- displayName: Images tag 
  description: tag of application image
  name: IMAGE_TAG
  required: false
objects:
# DEPLOYMNETCONFIG
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${DEV_PROJECT}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      app: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - env: []
          image: ${QUAY_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
          resources:
            limits:
              cpu: ${{CPU}}
              memory: ${MEMORY}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
# BUILDCONFIG
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
      build: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${DEV_PROJECT} 
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      pushSecret:
        name: ${APP_NAME}-secret
      to:
        kind: DockerImage
        name: ${QUAY_REPOSITORY}:${IMAGE_TAG}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM quay.io/bitnami/tomcat
        COPY ROOT.war /app
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: tomcat:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
# SERVICE
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${DEV_PROJECT}
  spec:
    ports:
    - name: http-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
# ROUTE
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${DEV_PROJECT}
  spec:
    port:
      targetPort: http-port
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
# QUAY.IO APP SECRET
- apiVersion: v1
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoiZW5uaW90b3JyZStvc2J1aWxkZXIiLCJwYXNzd29yZCI6IjIzUVAwT0tNV0NLREtQQ1JNVVREMVc0RFI2WjM2WFA0N1lRS0JHRURHWERBS1VYV05WVVBTU1FZRlc3U09STEwiLCJhdXRoIjoiWlc1dWFXOTBiM0p5WlN0dmMySjFhV3hrWlhJNk1qTlJVREJQUzAxWFEwdEVTMUJEVWsxVlZFUXhWelJFVWpaYU16WllVRFEzV1ZGTFFrZEZSRWRZUkVGTFZWaFhUbFpWVUZOVFVWbEdWemRUVDFKTVRBPT0ifX19
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
    namespace: ${DEV_PROJECT}
  type: kubernetes.io/dockerconfigjso
# QUAY.IO PIPE SECRET
- apiVersion: v1
  data:
    password: MjNRUDBPS01XQ0tES1BDUk1VVEQxVzREUjZaMzZYUDQ3WVFLQkdFREdYREFLVVhXTlZVUFNTUVlGVzdTT1JMTA==
    username: ZW5uaW90b3JyZStvc2J1aWxkZXI=
  kind: Secret
  metadata:
    labels:
      credential.sync.jenkins.openshift.io: "true"
    name: quay-cicd-secret
    namespace: ${DEV_PROJECT}
  type: Opaque